#<Etsy::Listing:0x007f8ac2b63538 
@result={"shop_id"=>7238701, 
        "listing_id"=>120967508, 
        "state"=>"active", 
        "user_id"=>24400171, 
        "category_id"=>69150467, 
        "title"=>"CREEPER from Minecraft vinyl decal stickers 2 x 4&quot; car truck laptop - two decals", 
        "description"=>"Minecraft Creeper face digitally cut from a quality vector graphic to a quality 5-7 yr outdoor rated vinyl. Perfect for any smooth surface and will conform to curved shapes. Quick and easy application: Just peel and apply. Long-lasting, safe, washable and outdoor element resistant.\r\n\r\nThis is for 2 Decals , 4x4 inches\r\n\r\nGreat for your Laptop, PC, car, motorcycle or minecraft house\r\nShip immediately", 
        "creation_tsz"=>1362701523, 
        "ending_tsz"=>1373169600, 
        "original_creation_tsz"=>1358604631, 
        "last_modified_tsz"=>1362701523, 
        "price"=>"2.99", 
        "currency_code"=>"USD", 
        "quantity"=>96, 
        "tags"=>["minecraft", "creeper", "minecraft birthday", "minecraft game", "decal", "sticker", "minecraft decal", "wall decoration", "creeper decal", "creeper sticker", "minecraft sticker", "creeper game"], 
        "category_path"=>["Accessories"], 
        "category_path_ids"=>[69150467], 
        "materials"=>[], 
        "shop_section_id"=>12921577, 
        "featured_rank"=>0, 
        "state_tsz"=>1358604631, 
        "url"=>"http://www.etsy.com/listing/120967508/creeper-from-minecraft-vinyl-decal?utm_source=listingsfeed&utm_medium=api&utm_campaign=api", 
        "views"=>160, 
        "num_favorers"=>10, 
        "shipping_profile_id"=>158618844, 
        "processing_min"=>1, 
        "processing_max"=>1, 
        "who_made"=>"i_did", 
        "is_supply"=>"false", 
        "when_made"=>"made_to_order", 
        "recipient"=>nil, 
        "occasion"=>nil, 
        "style"=>nil, 
        "non_taxable"=>false}, 
@token=nil, @secret=nil>
